default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails_tic_tac_toe_development

test:
  <<: *default
  database: rails_tic_tac_toe_test

production:
  <<: *default
  database: rails_tic_tac_toe_production
  username: rails_tic_tac_toe
  password: <%= ENV['RAILS_TIC_TAC_TOE_DATABASE_PASSWORD'] %>
